# Generated by Django 5.1.3 on 2024-11-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
