# Generated by Django 5.1.3 on 2024-11-20 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='DNI must be 7 or 8 digits', regex='^\\d{7, 8}$')]),
        ),
    ]
